#!/usr/bin/bash -ex

dnf install -y iptables-services bind-utils docker docker-compose git bzip2

systemctl --now enable iptables.service ip6tables.service
systemctl --now enable docker

HCLOUD_VOLUME_DATA=HC_Volume_${hcloud_volume_data_id}

if [ ! -e /mnt/data ] && [ -d /mnt/\$HCLOUD_VOLUME_DATA ]; then
	ln -s /mnt/\$HCLOUD_VOLUME_DATA /mnt/data
fi

useradd -G docker dpsrv

[ -d ~dpsrv/.ssh ] || mkdir ~dpsrv/.ssh

echo "${hcloud_ssh_key_dpsrv}" >> ~dpsrv/.ssh/authorized_keys

chown -R dpsrv:dpsrv ~dpsrv/.ssh
chmod -R og-rwx ~dpsrv/.ssh

cat >> /usr/local/bin/dpsrv-init-projects.sh << _EOT_
#!/usr/bin/bash -ex

docker network ls | grep -q '^[^ ]*[ ]*dpsrv' || docker network create dpsrv

pushd /mnt/data/dpsrv
git clone https://github.com/maxfortun/git-openssl-secrets.git
pushd git-openssl-secrets
ln -s git-setenv-openssl-secrets-fs.sh git-setenv-openssl-secrets.sh
popd >/dev/null
git clone https://github.com/dpsrv/rc.git
. rc/bin/dpsrv.sh
dpsrv-git-clone
dpsrv-git-init-secrets 

[ -d ~dpsrv/.bashrc.d ] || mkdir ~dpsrv/.bashrc.d
echo '. /mnt/data/dpsrv/rc/bin/dpsrv.sh' > ~dpsrv/.bashrc.d/dpsrv

_EOT_

cat >> /usr/local/bin/dpsrv-init.sh << _EOT_
#!/usr/bin/bash -x

if floating_ip=\$(host hc-ash-1.dpsrv.me|awk '{ print \$4 }'); then

	if ! ip a s | grep -q \$floating_ip; then
		ip addr add \$floating_ip dev eth0
	fi

fi

if [ ! -d /mnt/data/dpsrv ]; then
	while [ -f ~/.config/openssl-salt ]; do
		echo "Waiting for ~/.config"
		sleep 2
	done

	mkdir -p /mnt/data/dpsrv
	cp -r ~root/{.config,.gitconfig} ~dpsrv/

	chown -R dpsrv:dpsrv ~dpsrv/{.config,.gitconfig} /mnt/data/dpsrv

	sudo -u dpsrv /usr/local/bin/dpsrv-init-projects.sh

fi 

_EOT_

chmod a+x /usr/local/bin/dpsrv-init*.sh

cat >> /usr/lib/systemd/system/dpsrv-init.service << _EOT_
[Unit]
Description=DPSRV init
Requires=multi-user.target
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/local/bin/dpsrv-init.sh

[Install]
WantedBy=multi-user.target 

_EOT_

cat >> /etc/sudoers.d/dpsrv << _EOT_
dpsrv ALL=(ALL) NOPASSWD:/sbin/iptables,/sbin/ip6tables,/sbin/iptables-save,/sbin/ip6tables-save,/usr/bin/tee /etc/sysconfig/iptables,/usr/bin/tee /etc/sysconfig/ip6tables
_EOT_

systemctl --now enable dpsrv-init

