#!/bin/bash -ex

echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
systemctl restart systemd-resolved

dnf install -y dnf-plugins-core iptables-services ipset policycoreutils-python-utils setools-console setroubleshoot-server bind-utils nc git bzip2 tcpdump cronie fail2ban
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl --now enable iptables.service ip6tables.service
systemctl --now enable fail2ban
systemctl --now enable docker

HCLOUD_VOLUME_DATA=HC_Volume_${hcloud_volume_data_id}

if [ ! -e /mnt/data ] && [ -d /mnt/\$HCLOUD_VOLUME_DATA ]; then
	ln -s /mnt/\$HCLOUD_VOLUME_DATA /mnt/data
fi

for user in dpsrv ezsso; do
	useradd -G docker $user

	[ -d /home/$user/.ssh ] || mkdir /home/$user/.ssh

	echo "${hcloud_ssh_key_dpsrv}" >> /home/$user/.ssh/authorized_keys

	chown -R $user:$user /home/$user/.ssh
	chmod -R og-rwx /home/$user/.ssh

	[ -d /home/$user/.bashrc.d ] || mkdir /home/$user/.bashrc.d
	echo ". /mnt/data/dpsrv/rc/bin/dpsrv.sh" > /home/$user/.bashrc.d/dpsrv
	[ $user = dpsrv ] || echo ". /mnt/data/$user/rc/bin/$user.sh" > /home/$user/.bashrc.d/$user
done

cat >> /usr/local/bin/dpsrv-init-projects.sh << _EOT_
#!/bin/bash -ex

docker network ls | grep -q '^[^ ]*[ ]*dpsrv' || docker network create dpsrv

pushd /mnt/data/dpsrv
git clone https://github.com/maxfortun/git-openssl-secrets.git
pushd git-openssl-secrets
ln -s git-setenv-openssl-secrets-fs.sh git-setenv-openssl-secrets.sh
popd >/dev/null
git clone https://github.com/dpsrv/rc.git
. rc/bin/dpsrv.sh
dpsrv-git-clone
dpsrv-git-init-secrets 

dpsrv-up

_EOT_

cat >> /usr/local/bin/dpsrv-init.sh << _EOT_
#!/bin/bash -ex

if floating_ip=\$(host hc-ash-1.dpsrv.me|awk '{ print \$4 }'); then

	if ! ip a s | grep -q \$floating_ip; then
		ip addr add \$floating_ip dev eth0
	fi

fi

sysctl -w net.ipv4.conf.all.route_localnet=1
iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE -m comment --comment dpsrv:forward:port

while [ -f ~/.config/openssl-salt ]; do
	echo "Waiting for ~/.config"
	sleep 2
done

for user in dpsrv ezsso; do
	[ ! -d /mnt/data/\$user ] || continue
	mkdir -p /mnt/data/\$user
	cp -r ~root/{.config,.gitconfig} /home/\$user/

	chown -R \$user:\$user /home/\$user/{.config,.gitconfig} /mnt/data/\$user
done

sudo -u dpsrv /usr/local/bin/dpsrv-init-projects.sh

_EOT_

chmod a+x /usr/local/bin/dpsrv-init*.sh

cat >> /usr/lib/systemd/system/dpsrv-init.service << _EOT_
[Unit]
Description=DPSRV init
Requires=multi-user.target
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/local/bin/dpsrv-init.sh

[Install]
WantedBy=multi-user.target 

_EOT_

cat >> /etc/sudoers.d/dpsrv << _EOT_
dpsrv ALL=(ALL) NOPASSWD:/sbin/iptables,/sbin/ip6tables,/sbin/iptables-save,/sbin/ip6tables-save,/usr/bin/tee /etc/sysconfig/iptables,/usr/bin/tee /etc/sysconfig/ip6tables
_EOT_

systemctl --now enable dpsrv-init

